import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

const condensed = Lato({
  weight: ["400", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={condensed.className + " text-gray-50"}>{children}</body>
    </html>
  );
}
