import { NavBar } from "@/components/home/navbar";
import { ProgressBarProvider } from "@/components/home/progress-bar";
import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "./globals.css";

const roboto = Roboto_Condensed({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ backgroundImage: "url('/assets/nnnoise.svg')" }}
        className={
          roboto.className +
          " bg-background text-foreground selection:bg-primary selection:text-primary-foreground"
        }
      >
        <ProgressBarProvider>
          <>
            {/* <Banner /> */}
            <NavBar />
            {children}
          </>
        </ProgressBarProvider>
      </body>
    </html>
  );
}
